In [1]:
import pandas as pd
import numpy as np

# Answers to Exercises

**Exercise**: How would you sum the 3rd and 4th element of v?

In [8]:
v = np.array([1, 2, 3, 4, 5])
summed = v[2] + v[3]

**Exercise:** What if you wanted the 3x3 matrix at the left of A (everything but the rightmost column)?

In [9]:
random = np.random.randn(3, 4)
bigger_random = random * 10
A = bigger_random.astype(int)
A

array([[  0,  -3,  -3,  -1],
       [-11,  -3,   4,  -6],
       [  8,  20,   1, -14]])

In [10]:
A[0:3, 0:3]

array([[  0,  -3,  -3],
       [-11,  -3,   4],
       [  8,  20,   1]])

**Exercise:** Let's try to select the 2x2 matrix at the bottom righthand corner of the A matrix from the last exercise.

Like before, leaving the 2nd argument blank in both slices below tells it to run all the way to the end.

In [11]:
A[-2:, -2:]

array([[  4,  -6],
       [  1, -14]])

**Exercise:** What if we want to add a constant vector to each row of a matrix? In the following example, the sizes of the arrays are different, so the sum is performed elementwise. We want to create a `row_vector` that when added to `an_array`, returns the `given` matrix.

In [12]:
vector = np.array([1, 0, 1])

**Exercise:** Let's try an example with another 2D matrix. Uncomment A (again by deleting the #) and erase the underscore blanks, filling in numbers to make the output equal to ```[3, 12, 8]```.

In [13]:
A = [[2, 3, 5], [1, 9, 3]]

**Exercise:** What if we only want the numbers that are less than the mean of all the elements of the matrix?

In [15]:
random_matrix = np.random.rand(3, 3)
random_matrix[random_matrix > random_matrix.mean()]

array([ 0.88378525,  0.80366141,  0.89747615,  0.5627162 ])

### Indexing & Axis

**Exercise:** Given the `rounded_matrix` below, first retrieve only the first 3 columns; name this `halved_matrix`. Then sum the `halved_matrix` row wise.

In [20]:
rounded_matrix = np.random.randn(4, 6).astype(int)
rounded_matrix

array([[-2, -1,  1,  1,  0, -1],
       [ 0,  0,  0,  0,  1,  0],
       [ 0, -1,  0, -1,  0,  1],
       [ 0,  0,  0,  0,  0,  0]])

In [21]:
halved_matrix = rounded_matrix[:, :3]
row_sums = halved_matrix.sum(axis=1)

### Broadcasting

**Exercise:** Uncomment the x and fill in the 2 blanks so that x + y = z.

In [22]:
x = np.array([1, 2])

### Conditioning

We have 2 arrays, an array `x` consisting of some numbers and an array `y` consisting of letters that correspond to each number. Let's say we only want the letters whose numbers are negative. How would we do that?

In [23]:
y[x < 0]

NameError: name 'y' is not defined

## Pandas

In [24]:
# importing titanic dataset
titanic_train = pd.read_csv('titanic/train.csv')
titanic_test = pd.read_csv('titanic/test.csv')

### Filtering &  Sorting

**Exercise**: Find the total fare spent by females aboard the Titanic.

In [27]:
fare = titanic_train[titanic_train['Sex'] == 'female']['Fare'].sum()
fare

13966.66279999999

### Grouping & Aggregate Functions

**Exercise:** Find the mean age of males and females on the titanic.

In [30]:
titanic_train.groupby("Sex")[['Age']].mean()

Age
Sex              
female  27.915709
male    30.726645

### Pivoting

**Excercise**: Find the average age of passengers who did/didn't survive for each ticket class.

In [8]:
pd.pivot_table(titanic_train,
               index='Pclass',         # Index for rows
               columns='Survived',        # Columns
               values='Age',        # Values in table
               aggfunc=np.mean) # Aggregation function

Survived          0          1
Pclass                        
1         43.695312  35.368197
2         33.544444  25.901566
3         26.555556  20.646118